<a href="https://colab.research.google.com/github/Celinekimm/DeepLearning/blob/main/Dense_Layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.math import exp
from tensorflow.linalg import matmul

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
Y_tf= dense(X)

W, B = dense.get_weights()
print("Y(Tensorflow): \n", Y_tf.numpy())

# calculate with matrix multiplication
Z = matmul(X, W) + B
Y_man_matmul = 1/(1 + exp(-Z))
print("Y(with matrix mlitiplication: \n", Y_man_matmul.numpy())

Y(Tensorflow): 
 [[0.65565443 0.25478333 0.7557909 ]
 [0.81352764 0.18714339 0.6243402 ]
 [0.41831446 0.4628297  0.43577582]
 [0.67262816 0.53900284 0.6872364 ]]
Y(with matrix mlitiplication: 
 [[0.65565443 0.25478333 0.7557908 ]
 [0.81352764 0.18714339 0.6243402 ]
 [0.41831443 0.4628297  0.43577582]
 [0.67262816 0.53900284 0.6872364 ]]


## Cascade Dense Layers

In [15]:
N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [3, 5]
dense1 = Dense(units=n_neurons[0], activation='sigmoid')
dense2 = Dense(units=n_neurons[1], activation='sigmoid')

# forward propagation
A1 = dense1(X)
Y = dense2(A1)

# get weight/bias
W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()

print("X: {}\n".format(X.shape))

print("W1: ", W1.shape)
print("B1: ", B1.shape)
print("A1: {}\n".format(A1.shape))

print("W2: ", W2.shape)
print("B2: ", B2.shape)

print("Y: {}".format(Y.shape))

X: (4, 10)

W1:  (10, 3)
B1:  (3,)
A1: (4, 3)

W2:  (3, 5)
B2:  (5,)
Y: (4, 5)


## Dense Layers with Python List

In [25]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))
n_neurons = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

dense_layers = list()
for n_neuron in n_neurons:
  dense = Dense(units=n_neuron, activation='relu')
  dense_layers.append(dense)

print("Input: ", X.shape)
for dense_idx, dense in enumerate(dense_layers):
    X = dense(X)
    print("After dense layer", dense_idx+1)
    print(X.shape, '\n')


Input:  (4, 10)
After dense layer 1
(4, 10) 

After dense layer 2
(4, 20) 

After dense layer 3
(4, 30) 

After dense layer 4
(4, 40) 

After dense layer 5
(4, 50) 

After dense layer 6
(4, 60) 

After dense layer 7
(4, 70) 

After dense layer 8
(4, 80) 

After dense layer 9
(4, 90) 

After dense layer 10
(4, 100) 



## Output Calculations

In [30]:
N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))
X_cp = tf.identity(X)

n_neurons = [3, 4, 5]

dense_layers = list()
for n_neuron in n_neurons:
  dense = Dense(units=n_neuron, activation='sigmoid')
  dense_layers.append(dense)

# forward propagation(Tensorflow)
W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers):
    X = dense(X)
    w, b = dense.get_weights()

    W.append(w)
    B.append(b)
print("Y(Tensorflow: \n", X.numpy())

# get weight/bias
W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()



Input:  (4, 10)
Y(Tensorflow: 
 [[0.61173403 0.5357505  0.38835824 0.49689215 0.53415155]
 [0.60162586 0.55127937 0.3890557  0.49882594 0.5394065 ]
 [0.61833394 0.5271613  0.37999332 0.4925075  0.5408832 ]
 [0.60115236 0.54306304 0.39086658 0.49663234 0.5392636 ]]
